# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DarwinBrew < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.20.6"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.20.6/entropiq_1.20.6_darwin_amd64.tar.gz"
    sha256 "3df6f73e00a86ab9bb1b6e8e47056bdfeeac458ff797693d6bed16d20599be42"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.20.6/entropiq_1.20.6_darwin_arm64.tar.gz"
    sha256 "5b0c75dd99441de7ab5055c5eb4e05d8bff2e655bf677252a1a8e4398be90d70"

    def install
      bin.install "entropiq"
    end
  end

  test do
    system "entropiq", "--version"
  end
end
