# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT12252 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.52"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.52/entropiq_1.22.52_darwin_amd64"
    sha256 "c8bca21e92bf990003bc1d9f599a0dd4a0285dc5547a6cbddbd0b28bcc2748ac"

    def install
      bin.install "entropiq_1.22.52_darwin_amd64" => "release/mac/amd64/binary/entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.52/entropiq_1.22.52_darwin_arm64"
    sha256 "8579eef66bd9e21680b9fd4373ac67671e536bce20f87060d4b32c1c2eba1f29"

    def install
      bin.install "entropiq_1.22.52_darwin_arm64" => "release/mac/arm64/binary/entropiq"
    end
  end
end
