# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT12225 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.25"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.25/entropiq_1.22.25_darwin_amd64.tar.gz"
    sha256 "f1723bbc65debefde7e3cca9c0d87041a88a7e0f655870f6ccaec779758277ca"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.25/entropiq_1.22.25_darwin_arm64.tar.gz"
    sha256 "4749af40b80de9be4df9d81718c3012b4ca569cedf06928e3a644a9d5d504475"

    def install
      bin.install "entropiq"
    end
  end

  test do
    system "entropiq", "--version"
  end
end
