# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT12238 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.38"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.38/entropiq_1.22.38_darwin_amd64"
    sha256 "66385e05e7ed5f2541170db7eab59420213f877cb66c541a2b5a24f638fa13fb"

    def install
      bin.install "entropiq_1.22.38_darwin_amd64" => "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.38/entropiq_1.22.38_darwin_arm64"
    sha256 "dd8f77cee254ddb9459982d570c4d7b0c42336027ec014da096287cf0c57fd95"

    def install
      bin.install "entropiq_1.22.38_darwin_arm64" => "entropiq"
    end
  end
end
