# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT12217 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.17"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.17/entropiq_1.22.17_darwin_amd64.tar.gz"
    sha256 "a55bfdf8057d879593ea1e9c4dc6f1ac59830ca9e9e85f4404034e8bd736fd3c"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.17/entropiq_1.22.17_darwin_arm64.tar.gz"
    sha256 "6dc4d526cf53335a2350ca86a3343fca0033dd6f97f022ac8ebfa373fa76bbce"

    def install
      bin.install "entropiq"
    end
  end

  test do
    system "entropiq", "--version"
  end
end
