# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT12229 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.29"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.29/entropiq_1.22.29_darwin_amd64.tar.gz"
    sha256 "5dfcd03009dca9dc53699034de97062351ed4749c826ebc4941348ef3f551f27"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.29/entropiq_1.22.29_darwin_arm64.tar.gz"
    sha256 "ad0cea804a75c6bfe9b160ede18768614bf6a5f9a1fc5f023163db27b1275a1a"

    def install
      bin.install "entropiq"
    end
  end
end
