# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT186 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.8.6"

  depends_on "qemu"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.8.6/entropiq_1.8.6_darwin_arm64.tar.gz"
    sha256 "f8b976b2bb1583403bb064a867c089185d7e5f9fb93c37b176d49cb58821f090"

    def install
      bin.install "entropiq"
    end
  end

  test do
    system "entropiq", "--version"
  end
end
