# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT1816 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.8.16"

  depends_on "qemu"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.8.16/entropiq_1.8.16_darwin_amd64.tar.gz"
    sha256 "ff33447ce49017728b3dd7d3ef40ee839ec0fda240572558441d3b2d2eb5d35e"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.8.16/entropiq_1.8.16_darwin_arm64.tar.gz"
    sha256 "2892dd72127c4bfff228d615dcd6493b1bb996b2cad5f77d3ec2448f0d3a047f"

    def install
      bin.install "entropiq"
    end
  end

  test do
    system "entropiq", "--version"
  end
end
