# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT1015 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.0.15"

  depends_on "qemu"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.0.15/entropiq_1.0.15_darwin_arm64.tar.gz"
    sha256 "0b653db799aee00207a02128be2d201aaee25f412d2a27fa31d83b0674c61570"

    def install
      bin.install "entropiq"
    end
  end

  test do
    system "entropiq", "--version"
  end
end
