# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT184 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.8.4"

  depends_on "qemu"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.8.4/entropiq_1.8.4_darwin_arm64.tar.gz"
    sha256 "aa52eef4fa59ddd15c3cd29fe22391027a5f32270a42a7d5144ac62276ff45b9"

    def install
      bin.install "entropiq"
    end
  end

  test do
    system "entropiq", "--version"
  end
end
