# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT11819 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.18.19"

  depends_on "qemu"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.18.19/entropiq_1.18.19_darwin_amd64.tar.gz"
    sha256 "d09e39fffb7d1def9140c058da7d6c24aac1584354b9d4dc2649d01c4f4f42a4"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.18.19/entropiq_1.18.19_darwin_arm64.tar.gz"
    sha256 "9608020f6619d5b3edcd2e57f56968a66873826cc75812ca670f90eb5af2f20c"

    def install
      bin.install "entropiq"
    end
  end

  test do
    system "entropiq", "--version"
  end
end
