# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT1 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.8"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.8/entropiq_1.22.8_darwin_amd64.tar.gz"
    sha256 "28f769659a87764a30048baf11f428d67932b88de6752d33ae6c5a86dd766aa1"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.8/entropiq_1.22.8_darwin_arm64.tar.gz"
    sha256 "0b4955eff3af90c5d23fc3e0c09ed5acbebf51314e42fd26e905908cfde3314d"

    def install
      bin.install "entropiq"
    end
  end

  test do
    system "entropiq", "--version"
  end
end
