# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT12220 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.20"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.20/entropiq_1.22.20_darwin_amd64.tar.gz"
    sha256 "47179193ff388abd3ccf8a847bfd55b042075377e48e5237ecb330c8c812c7fe"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.20/entropiq_1.22.20_darwin_arm64.tar.gz"
    sha256 "ea0e24f0a016a48651bf845af8e2932f098fb02b41046816fb81f3577ada7245"

    def install
      bin.install "entropiq"
    end
  end

  test do
    system "entropiq", "--version"
  end
end
