# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT183 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.8.3"

  depends_on "qemu"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.8.3/entropiq_1.8.3_darwin_arm64.tar.gz"
    sha256 "2540798b0382be66e88b68b3e870346dc643570ee889aaba7d9293f778f8cff8"

    def install
      bin.install "entropiq"
    end
  end

  test do
    system "entropiq", "--version"
  end
end
