# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT12218 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.18"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.18/entropiq_1.22.18_darwin_amd64.tar.gz"
    sha256 "00c23460d5ffa235210da91dafe52d2a830066b53ca2f794e4c1ecae7d0c8981"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.18/entropiq_1.22.18_darwin_arm64.tar.gz"
    sha256 "cfaf587a9995bfd8dc5344aec30d1d2ca2d6b93e9410e620727a2d0e4a4b885a"

    def install
      bin.install "entropiq"
    end
  end

  test do
    system "entropiq", "--version"
  end
end
