# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT1 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.22.19"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.19/entropiq_1.22.19_darwin_amd64.tar.gz"
    sha256 "eb2c9ce0c024510ef54b60c96c21c66b1b7bbecdfd5944587ca3187a95728b46"

    def install
      bin.install "entropiq"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.22.19/entropiq_1.22.19_darwin_arm64.tar.gz"
    sha256 "cb7b17bf5f39f27a2d325df2e206d4a0baaa254b311ff2b0d825e00a75eef926"

    def install
      bin.install "entropiq"
    end
  end

  test do
    system "entropiq", "--version"
  end
end
