# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EntropiqAT1019 < Formula
  desc "The EntropiQ CLI."
  homepage "https://entropiq.com"
  version "1.0.19"

  depends_on "qemu"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/parallelinc/entropiq-binary-cli/releases/download/1.0.19/entropiq_1.0.19_darwin_arm64.tar.gz"
    sha256 "9f3e0d85786175320a05c186ed65d84f0f63c638cb25d50684d643b079f50cb4"

    def install
      bin.install "entropiq"
    end
  end

  test do
    system "entropiq", "--version"
  end
end
